name: www
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - sqlalchemy
  - mysql-connector-python
  - conda-forge::overpy
  - conda-forge::pymysql
  - pymssql
  - numpy
  - matplotlib 
  - seaborn 
  - requests
  - requests-cache
  - pyodbc
  - ipykernel
  - urllib
  - math
  - pip
  - pip:
    - openmeteo_requests
    - retry-requests
    - opencage